#!/bin/bash

source=${1}
dest=${2}
count=0
for word in `cat ${dest}`; do
	if [ ${word} = ${source} ]; then
		count=$((count+1))
	fi
done

echo "word: ${source} appears in file: ${dest} ${count} times."
